# Generated by Django 4.2.7 on 2025-07-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('donated', 'Donated'), ('expired', 'Expired')], default='available', max_length=20),
        ),
    ]
