# Generated by Django 4.2.7 on 2025-07-23 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0002_donation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Store name, restaurant name, or business name', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('business_hours', models.TextField(blank=True, help_text='e.g., Mon-Fri 9AM-6PM, Sat 10AM-4PM')),
                ('business_type', models.CharField(blank=True, help_text='e.g., Restaurant, Grocery Store, Bakery, Home Cook', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of your business or organization')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified business/organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
