# Generated by Django 4.2.7 on 2025-07-23 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='business_image',
            field=models.ImageField(blank=True, help_text='Upload a photo of your business/store/restaurant (optional)', null=True, upload_to='donor_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
